### ISSUE TITLE
Add navigation for our site

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/ScrimbaBootcamp2024#10]
We have a number of HTML files. How can we get to them from the home page (or from any of the pages, for that matter)? We need a `<nav>` element. Responsiveness isn't imperative at this point. We can create a new issue for styling the `<nav>`.

**Comment by tak40** [comment]
Hi Micha,

I hope this is the right place to ask. I'm interested in contributing to this 'Add navigation for our site' issue (Issue #10). Could you assign it to me if it hasn't been taken yet?

Also, I want to ensure I understand the scope correctly. Are "Home", "Resources", "Blog", and "About" the only pages we're including in the navigation bar, or are there any others?

Thank you,
Tak

**Comment by michaella23** [comment]
Hey Tak! You can work on this issue, but we haven't created all the files yet. That is a separate issue (#5). Can you create the `nav` and just use a placeholder for the `href` attributes?

**Comment by tak40** [comment]
Oops, I didn't pay close attention to the part about the files not all being ready yet. 😅 How about I jump in on Issue #5 first and set up the basic layout? That way, we can have a nice foundation to build our navigation links on. I think it makes sense to have those placeholders in place beforehand. Let me know if that sounds good to you!

**Comment by dmora219** [comment]
I seen the confusion on comments! if tak hasnt been assigned this ill like to do it @michaella23

**Comment by michaella23** [comment]
@dmora219 I assigned @tak40 already. Tak, do you still want to complete this ticket? (No rush!) Just let us know if not, and I'll reassign it to David. 🙂

**Comment by tak40** [comment]
Sorry for the late reply! I was out all day today. Can I get it done tomorrow if that's okay? If David wants to take over, that's fine too. I can take on other tickets :)
