### ISSUE TITLE
Add more HTML files

### ISSUE THREAD

**Issue by michaella23** [ScrimbaBootcamp/ScrimbaBootcamp2024#5]
We will have an 'About' page, a 'Resources' page, and a 'Blog' page. Create these files and add HTML boilerplate code for each.

**Comment by tak40** [comment]
My apologies for the mix-up earlier! I'm now ready to work on setting up the HTML files for the 'About', 'Resources', and 'Blog' pages. Could you assign this issue to me so I can get started?

I'll make sure to add the HTML boilerplate code for each page. Once that's done, it'll be smooth sailing to link them up with the navigation bar. Thanks for your patience and guidance!

**Comment by michaella23** [comment]
Go for it @tak40! Thank you!
